### ISSUE TITLE
Missing parse_resource.yml file

### ISSUE THREAD

**Issue by adxicible** [CodeCampKK/FrocBorneo#1]
forgot to commit ? :p

**Comment by tslim** [comment]
@namor does parse_resource.yml have the token in it? If yes, commit an example?

@adxicible If it has auth/API token in it, we don't usually commit into the database.

**Comment by namor** [comment]
Added an example  in b7d52e9bbbf0d42d414dad0ca859b01e8c7081fa

**Comment by adxicible** [comment]
Email me the file then

**Comment by namor** [comment]
Just fetch you can see the example file

**Comment by adxicible** [comment]
Ok.. thank you 😀
